info:
  app:
    description: Demo ports and adapters project
    name: HexBike
    version: 0.0.1-SNAPSHOT

io:
  redintro:
    scheduling:
      enabled: true
      frequency:
        pattern: 0 */1 * * * ?
      lock:
        atLeastFor: PT30S
        atMostFor: PT30S
        nameSpace: hexbike

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: docker
    url: jdbc:postgresql://localhost:5432/hexbike_dev
    username: docker
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379

springdoc:
  api-docs:
    path: /api-docs
